### ISSUE TITLE
css-what has Denial of Service

### ISSUE THREAD

**Issue by hawkeye64** [fb55/css-what#519]
```bash
# npm audit report

css-what  <5.0.1
Severity: high
Denial of Service - https://npmjs.com/advisories/1754
No fix available
```

When a fix is available, it is going to take a while for this upstream project to make it to us.

```bash
=> Found "svgo#css-what@4.0.0"
info Reasons this module exists
   - "@quasar#app#cssnano#cssnano-preset-default#postcss-svgo#svgo#css-select" depends on it
   - Hoisted from "@quasar#app#cssnano#cssnano-preset-default#postcss-svgo#svgo#css-select#css-what"
```

We have 5 levels that will need the update before we can get it. :(

**Comment by fb55** [comment]
Hi @hawkeye64, I know this is highly annoying. You should be safe to ignore this, as the issue is only present when parsing user-provided css selectors and I assume you don't run cssnano on user input.

Unfortunately there isn't anything I can do here but hope that all packages manage to release new versions soon.

**Comment by hawkeye64** [comment]
It's just all of the users of our Quasar Framework started seeing this today and quite a few are "spooked". I'll pass on your info, thanks.
